var fish = [
  {"name": 'Bitterling',
"location": 'River',
"size": "smallest",
"value": 900,
"start time": 0,
"end time": 0,
"months": ['Nov', 'Dec', 'Jan', 'Mar'],
"rare": false
},
{"name": 'Pale Chub',
"location": 'River',
"size": 'smallest',
"value": 160,
"start time": 9,
"end time": 16,
"months": ['Year-round'],
"rare": false
},
{"name": 'Crucian Carp',
"location": 'River',
"size": 'small',
"value": 160,
"start time": 0,
"end time": 0,
"months": ['Year-round'],
"rare": false
},
{"name": 'Dace',
"location": 'River',
"size": 'Medium',
"value": 240,
"start time": 16,
"end time": 9,
"months": ['Year-round'],
"rare": false
},
{"name": 'Carp',
"location": 'pond',
"size": 'large',
"value": 300,
"start time": 0,
"end time": 0,
"months": ['Year-round'],
"rare": false
},
{"name": 'Koi',
"location": 'pond',
"size": 'large',
"value": 4000,
"start time": 16,
"end time": 9,
"months": ['Year-round'],
"rare": true
},
{"name": 'Goldfish',
"location": 'pond',
"size": 'smallest',
"value": 1300,
"start time": 0,
"end time": 0,
"months": ['Year-round'],
"rare": false
},
{"name": 'Pop-eyed Goldfish',
"location": 'pond',
"size": 'smallest',
"value": 1300,
"start time": 9,
"end time": 16,
"months": ['Year-round'],
"rare": false
},
{"name": 'Ranchu Goldfish',
"location": 'pond',
"size": 'small',
"value": 4500,
"start time": 9,
"end time": 16,
"months": ['Year-round'],
"rare": true
},
{"name": 'Killifish',
"location": 'pond',
"size": 'smallest',
"value": 300,
"start time": 0,
"end time": 0,
"months": ['Apr', 'May', 'Jun', 'Jul', 'Aug'],
"rare": false
},
{"name": 'Crawfish',
"location": 'pond',
"size": 'small',
"value": 200,
"start time": 0,
"end time": 0,
"months": ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
"rare": false
},
{"name": 'Soft-shelled Turtle',
"location": 'river',
"size": 'large',
"value": 3750,
"start time": 16,
"end time": 9,
"months": ['Aug', 'Sep'],
"rare": false
},
{"name": 'Snapping Turtle',
"location": 'river',
"size": 'extra large',
"value": 5000,
"start time": 21,
"end time": 4,
"months": ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
"rare": false
},
{"name": 'Tadpole',
"location": 'pond',
"size": 'smallest',
"value": 100,
"start time": 0,
"end time": 0,
"months": ['Mar', 'Apr', 'May', 'Jun', 'Jul'],
"rare": false
},
{"name": 'Frog',
"location": 'pond',
"size": 'small',
"value": 120,
"start time": 0,
"end time": 0,
"months": ['May', 'Jun', 'Jul', 'Aug'],
"rare": false
},
{"name": 'Freshwater Goby',
"location": 'river',
"size": 'small',
"value": 400,
"start time": 16,
"end time": 9,
"months": ['Year-round'],
"rare": false
},
{"name": 'Loach',
"location": 'river',
"size": 'small',
"value": 400,
"start time": 0,
"end time": 0,
"months": ['Mar', 'Apr', 'May'],
"rare": false
},
{"name": 'Catfish',
"location": 'pond',
"size": 'large',
"value": 800,
"start time": 16,
"end time": 9,
"months": ['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
"rare": false
},
{"name": 'Giant Snakehead',
"location": 'pond',
"size": 'extra large',
"value": 5500,
"start time": 9,
"end time": 16,
"months": ['Jun', 'Jul', 'Aug'],
"rare": true
},
{"name": 'Bluegill',
"location": 'river',
"size": 'small',
"value": 180,
"start time": 9,
"end time": 16,
"months": ['Year-round'],
"rare": false
},
{"name": 'Yellow Perch',
"location": 'river',
"size": 'medium',
"value": 300,
"start time": 0,
"end time": 0,
"months": ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
"rare": false
},
{"name": 'Black Bass',
"location": 'river',
"size": 'large',
"value": 400,
"start time": 0,
"end time": 0,
"months": ['Year-round'],
"rare": false
},
{"name": 'Tilapia',
"location": 'river',
"size": 'medium',
"value": 800,
"start time": 0,
"end time": 0,
"months": ['Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
"rare": false
},
{"name": 'Pike',
"location": 'river',
"size": 'extra large',
"value": 1800,
"start time": 0,
"end time": 0,
"months": ['Sep', 'Oct', 'Nov', 'Dec']
},
{"name": 'Pond Smelt',
"location": 'river',
"size": 'small',
"value": 500,
"start time": 0,
"end time": 0,
"months": ['Dec', 'Jan', 'Feb'],
"rare": false
},
{"name": 'Sweetfish',
"location": 'river',
"size": 'medium',
"value": 900,
"start time": 0,
"end time": 0,
"months": ['Jul', 'Aug', 'Sep'],
"rare": false
},
{"name": 'Cherry Salmon',
"location": 'river clifftop',
"size": 'medium',
"value": 1000,
"start time": 16,
"end time": 9,
"months": ['Mar', 'Apr', 'May', 'Jun', 'Sep', 'Oct', 'Nov'],
"rare": false
},
{"name": 'Char',
"location": 'river clifftop',
"size": 'medium',
"value": 3800,
"start time": 16,
"end time": 9,
"months": ['Mar', 'Apr', 'May', 'Jun', 'Sep', 'Oct', 'Nov'],
"rare": false
},
{"name": 'Golden Trout',
"location": 'river clifftop',
"size": 'medium',
"value": 15000,
"start time": 16,
"end time": 9,
"months": ['Mar', 'Apr', 'May', 'Sep', 'Oct', 'Nov']
},
{"name": 'Stringfish',
"location": 'river clifftop',
"size": 'extra large',
"value": 15000,
"start time": 16,
"end time": 9,
"months": ['Dec', 'Jan', 'Feb', 'Mar'],
"rare": true
},
{"name": 'Salmon',
"location": 'river mouth',
"size": 'large',
"value": 700,
"start time": 0,
"end time": 0,
"months": ['Sep'],
"rare": false
},
{"name": 'King Salmon',
"location": 'river mouth',
"size": 'largest',
"value": 1800,
"start time": 0,
"end time": 0,
"months": ['Sep'],
"rare": false
},
{"name": 'Mitten Crab',
"location": 'river',
"size": 'small',
"value": 2000,
"start time": 16,
"end time": 9,
"months": ['Sep', 'Oct', 'Nov'],
"rare": false
},
{"name": 'Guppy',
"location": 'river',
"size": 'smallest',
"value": 1300,
"start time": 9,
"end time": 16,
"months": ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov'],
"rare": false
},
{"name": 'Nibble Fish',
"location": 'river',
"size": 'smallest',
"value": 1500,
"start time": 9,
"end time": 16,
"months": ['May', 'Jun', 'Jul', 'Aug', 'Sep'],
"rare": false
},
{"name": 'Angelfish',
"location": 'river',
"size": 'small',
"value": 3000,
"start time": 16,
"end time": 9,
"months": ['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
"rare": false
},
{"name": 'Betta',
"location": 'river',
"size": 'small',
"value": 2500,
"start time": 9,
"end time": 16,
"months": ['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
"rare": true
},
{"name": 'Neon Tetra',
"location": 'river',
"size": 'smallest',
"value": 500,
"start time": 9,
"end time": 16,
"months": ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov'],
"rare": false
},
{"name": 'Rainbowfish',
"location": 'river',
"size": 'smallest',
"value": 800,
"start time": 9,
"end time": 16,
"months": ['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
"rare": false
},
{"name": 'Piranha',
"location": 'river',
"size": 'small',
"value": 2500,
"start time": 9,
"end time": 16,
"months": ['Jun', 'Jul', 'Aug', 'Sep'],
"rare": false
},
{"name": 'Arowana',
"location": 'river',
"size": 'large',
"value": 10000,
"start time": 16,
"end time": 9,
"months": ['Jun', 'Jul', 'Aug', 'Sep'],
"rare": true
},
{"name": 'Dorado',
"location": 'river',
"size": 'extra large',
"value": 15000,
"start time": 4,
"end time": 21,
"months": ['Jun', 'Jul', 'Aug', 'Sep'],
"rare": true
},
{"name": 'Gar',
"location": 'pond',
"size": 'largest',
"value": 6000,
"start time": 16,
"end time": 9,
"months": ['Jun', 'Jul', 'Aug', 'Sep'],
"rare": true
},
{"name": 'Arapaima',
"location": 'river',
"size": 'largest',
"value": 10000,
"start time": 16,
"end time": 9,
"months": ['Jun', 'Jul', 'Aug', 'Sep'],
"rare": true
},
{"name": 'Saddled Bichir',
"location": 'river',
"size": 'large',
"value": 4000,
"start time": 21,
"end time": 4,
"months": ['Jun', 'Jul', 'Aug', 'Sep'],
"rare": true
},
{"name": 'Sturgeon',
"location": 'river mouth',
"size": 'largest',
"value": 10000,
"start time": 0,
"end time": 0,
"months": ['Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
"rare": true
},
{"name": 'Sea Butterfly',
"location": 'sea',
"size": 'smallest',
"value": 1000,
"start time": 0,
"end time": 0,
"months": ['Dec', 'Jan', 'Feb', 'Mar'],
"rare": false
},
{"name": 'Sea Horse',
"location": 'sea',
"size": 'smallest',
"value": 1100,
"start time": 0,
"end time": 0,
"months": ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov'],
"rare": false
},
{"name": 'Clown Fish',
"location": 'sea',
"size": 'smallest',
"value": 650,
"start time": 0,
"end time": 0,
"months": ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
"rare": false
},
{"name": 'Surgeonfish',
"location": 'sea',
"size": 'small',
"value": 1000,
"start time": 0,
"end time": 0,
"months": ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
"rare": false
},
{"name": 'Butterfly Fish',
"location": 'sea',
"size": 'small',
"value": 1000,
"start time": 0,
"end time": 0,
"months": ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
"rare": false
},
{"name": 'Napoleonfish',
"location": 'sea',
"size": 'largest',
"value": 10000,
"start time": 4,
"end time": 21,
"months": ['Jul', 'Aug'],
"rare": true
},
{"name": 'Zebra Turkeyfish',
"location": 'sea',
"size": 'medium',
"value": 500,
"start time": 0,
"end time": 0,
"months": ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov'],
"rare": false
},
{"name": 'Blowfish',
"location": 'sea',
"size": 'medium',
"value": 5000,
"start time": 21,
"end time": 4,
"months": ['Nov', 'Dec', 'Jan', 'Feb'],
"rare": false
},
{"name": 'Puffer Fish',
"location": 'sea',
"size": 'medium',
"value": 250,
"start time": 0,
"end time": 0,
"months": ['Jul', 'Aug', 'Sep'],
"rare": false
},
{"name": 'Anchovy',
"location": 'sea',
"size": 'small',
"value": 200,
"start time": 4,
"end time": 21,
"months": ['Year-round'],
"rare": false
},
{"name": 'Horse Mackerel',
"location": 'sea',
"size": 'small',
"value": 150,
"start time": 0,
"end time": 0,
"months": ['Year-round'],
"rare": false
},
{"name": 'Barred Knifejaw',
"location": 'sea',
"size": 'medium',
"value": 5000,
"start time": 0,
"end time": 0,
"months": ['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov'],
"rare": false
},
{"name": 'Sea Bass',
"location": 'sea',
"size": 'extra large',
"value": 400,
"start time": 0,
"end time": 0,
"months": ['Year-round'],
"rare": false
},
{"name": 'Red Snapper',
"location": 'sea',
"size": 'large',
"value": 3000,
"start time": 0,
"end time": 0,
"months": ['Year-round'],
"rare": false
},
{"name": 'Dab',
"location": 'sea',
"size": 'medium',
"value": 300,
"start time": 0,
"end time": 0,
"months": ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr'],
"rare": false
},
{"name": 'Squid',
"location": 'sea',
"size": 'medium',
"value": 500,
"start time": 0,
"end time": 0,
"months": ['Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
"rare": false
},
{"name": 'Moray Eel',
"location": 'sea',
"size": 'narrow',
"value": 2000,
"start time": 0,
"end time": 0,
"months": ['Aug', 'Sep', 'Oct'],
"rare": false
},
{"name": 'Ribbon Eel',
"location": 'sea',
"size": 'narrow',
"value": 600,
"start time": 0,
"end time": 0,
"months": ['Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
"rare": false
},
{"name": 'Tuna',
"location": 'pier',
"size": 'largest',
"value": 7000,
"start time": 0,
"end time": 0,
"months": ['Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr'],
"rare": true
},
{"name": 'Blue Marlin',
"location": 'pier',
"size": 'largest',
"value": 10000,
"start time": 0,
"end time": 0,
"months": ['Jul', 'Aug', 'Sep', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr'],
"rare": true
},
{"name": 'Giant Trevally',
"location": 'pier',
"size": 'extra large',
"value": 4500,
"start time": 0,
"end time": 0,
"months": ['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
"rare": true
},
{"name": 'Mahi-mahi',
"location": 'pier',
"size": 'extra large',
"value": 6000,
"start time": 0,
"end time": 0,
"months": ['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
"rare": true
},
{"name": 'Ocean Sunfish',
"location": 'sea',
"size": 'largest (fin)',
"value": 4000,
"start time": 4,
"end time": 21,
"months": ['Jul', 'Aug', 'Sep'],
"rare": false
},
{"name": 'Ray',
"location": 'sea',
"size": 'extra large',
"value": 3000,
"start time": 4,
"end time": 21,
"months": ['Aug', 'Sep', 'Oct', 'Nov'],
"rare": false
},
{"name": 'Saw Shark',
"location": 'sea',
"size": 'largest (fin)',
"value": 12000,
"start time": 16,
"end time": 9,
"months": ['Jun', 'Jul', 'Aug', 'Sep'],
"rare": true
},
{"name": 'Hammerhead Shark',
"location": 'sea',
"size": 'largest (fin)',
"value": 8000,
"start time": 16,
"end time": 9,
"months": ['Jun', 'Jul', 'Aug', 'Sep'],
"rare": true
},
{"name": 'Great White Shark',
"location": 'sea',
"size": 'largest (fin)',
"value": 15000,
"start time": 16,
"end time": 9,
"months": ['Jun', 'Jul', 'Aug', 'Sep'],
"rare": true
},
{"name": 'Whale Shark',
"location": 'sea',
"size": 'largest (fin)',
"value": 13000,
"start time": 0,
"end time": 0,
"months": ['Jun', 'Jul', 'Aug', 'Sep'],
"rare": true
},
{"name": 'Suckerfish',
"location": 'sea',
"size": 'large (fin)',
"value": 1500,
"start time": 0,
"end time": 0,
"months": ['Jun', 'Jul', 'Aug', 'Sep'],
"rare": false
},
{"name": 'Football Fish',
"location": 'sea',
"size": 'large',
"value": 2500,
"start time": 16,
"end time": 9,
"months": ['Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
"rare": false
},
{"name": 'Oarfish',
"location": 'sea',
"size": 'largest',
"value": 9000,
"start time": 0,
"end time": 0,
"months": ['Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May'],
"rare": true
},
{"name": 'Barreleye',
"location": 'sea',
"size": 'small',
"value": 15000,
"start time": 21,
"end time": 4,
"months": ['Year-round'],
"rare": true
}
]


fishFinder = function(fish){
  var valuable = {
    'name': null,
    'value': 0,
    'location': null,
    'size': null
  };
  var commonVal = {
    'name': null,
    'value': 0,
    'location': null,
    'size': null
  };
  var rightNow = new Date().toString();
  var currentMonth = rightNow.slice(4,7);
  var currentHour = parseInt(rightNow.slice(16, 18));
    for (var i = 0; i < fish.length; i++){
      var entry = fish[i];
      var startTime = entry['start time'];
      var endTime = entry['end time'];
      var months = entry['months'];
        if (startTime > endTime){
          if (currentHour > startTime && currentHour < 24 || currentHour >= 0 && currentHour < endTime){
            if (months.includes(currentMonth) || months === 'Year-round'){
              if (entry['value'] > valuable['value']){
              valuable['name'] = entry['name'];
              valuable['value'] = entry['value'];
              valuable['location'] = entry['location'];
              valuable['size'] = entry['size'];
              }
            if (!entry['rare'] && entry['value'] > commonVal['value']){
                commonVal['name'] = entry['name'];
                commonVal['value'] = entry['value'];
                commonVal['location'] = entry['location'];
                commonVal['size'] = entry['size'];
              }
            }
          }
          } else {
          if (currentHour > startTime && currentHour < endTime || startTime === endTime){
            if (entry['value'] > valuable['value']){
              valuable['name'] = entry['name'];
              valuable['value'] = entry['value'];
              valuable['location'] = entry['location'];
              valuable['size'] = entry['size'];
              }
            if (!entry['rare'] && entry['value'] > commonVal['value']){
                commonVal['name'] = entry['name'];
                commonVal['value'] = entry['value'];
                commonVal['location'] = entry['location'];
                commonVal['size'] = entry['size'];
              }
            }
          }
        }
        return [valuable, commonVal]
    }

